server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://sh-cdb-kc95luw2.sql.tencentcdb.com:60587/es?useSSL=false
    username: memory
    password: Guan213546@
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.wiki.hotel.pojo